services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wp_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../wordpress:/var/www/html
      - ../../app/themes:/var/www/html/wp-content/themes
      - ../../app/plugins:/var/www/html/wp-content/plugins
      - ../../app/uploads:/var/www/html/wp-content/uploads
      - ../logs:/var/log
      - ../conf/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
    restart: always
    networks:
      - wordpress

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: wp_mysql
    command: mysqld --skip-mysqlx --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ../database:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - wordpress
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    restart: always
    networks:
      - wordpress

networks:
  wordpress:
    driver: bridge